export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED"

export const REVIEW_ADD_REQUEST = "REVIEW_ADD_REQUEST"
export const REVIEW_ADD_SUCCESS = "REVIEW_ADD_SUCCESS"
export const REVIEW_ADD_FAILED = "REVIEW_ADD_FAILED"

//Cart types

export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

//Authentication

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED"

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILED = "USER_UPDATE_FAILED"
export const USER_UPDATE_RESET = "USER_UPDATE_RESET"

export const USER_LOGOUT = "USER_LOGOUT"

export const LOAD_USER_FROM_TOKEN_SUCCESS = "LOAD_USER_FROM_TOKEN_SUCCESS"
export const LOAD_USER_FROM_TOKEN_FAILED = "LOAD_USER_FROM_TOKEN_FAILED"

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"
export const DELETE_USER_FAILED = "DELETE_USER_FAILED"

//order
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAILED = "ORDER_DETAILS_FAILED"

export const MY_ORDER_DETAILS_REQUEST = "MY_ORDER_DETAILS_REQUEST"
export const MY_ORDER_DETAILS_SUCCESS = "MY_ORDER_DETAILS_SUCCESS"
export const MY_ORDER_DETAILS_FAILED = "MY_ORDER_DETAILS_FAILED"

export const MODIFY_ORDER_REQUEST = "MODIFY_ORDER_REQUEST"
export const MODIFY_ORDER_SUCCESS = "MODIFY_ORDER_SUCCESS"
export const MODIFY_ORDER_FAILED = "MODIFY_ORDER_FAILED"
