export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAILED = "PRODUCT_LIST_FAILED"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILED"

//Cart types

export const CART_ADD_ITEM = "CART_ADD_ITEM"
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM"

//Authentication

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"

export const USER_LOGOUT = "USER_LOGOUT"

export const LOAD_USER_FROM_TOKEN_SUCCESS = "LOAD_USER_FROM_TOKEN_SUCCESS"
export const LOAD_USER_FROM_TOKEN_FAILED = "LOAD_USER_FROM_TOKEN_FAILED"
